### ISSUE TITLE
LightChat or something not working idk

### ISSUE THREAD

**Issue by rackgaming** [Creeperface01/PlaceholderAPI-nukkit#16]
`cn.nukkit.utils.EventException: null
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:543) [server.jar:?]
        at cn.nukkit.Player.chat(Player.java:3729) [server.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2928) [server.jar:?]
        at cn.nukkit.network.session.RakNetPlayerSession.serverTick(RakNetPlayerSession.java:153) [server.jar:?]
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:89) [server.jar:?]
        at cn.nukkit.network.Network.processInterfaces(Network.java:165) [server.jar:?]
        at cn.nukkit.Server.tick(Server.java:1164) [server.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:940) [server.jar:?]
        at cn.nukkit.Server.start(Server.java:908) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:589) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
Caused by: java.lang.IncompatibleClassChangeError: Method 'com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI.getInstance()' must be Methodref constant
        at me.petterim1.lightchat.API.a(API.java:37) ~[?:?]
        at me.petterim1.lightchat.Events.a(Events.java:76) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
        ... 12 more`

**Comment by Creeperface01** [comment]
Report this to LightChat developer
