### ISSUE TITLE
on the china not work

### ISSUE THREAD

**Issue by D3it7i** [Creeperface01/PlaceholderAPI-nukkit#2]
2019-1-31 06:06:57 [INFO] 读取中... PlaceholderAPI v1.2
2019-1-31 06:06:57 [INFO] [PlaceholderAPI] Downloading KotlinLib...
2019-1-31 06:06:57 [INFO] Epoll is available. EpollEventLoop will be used.
2019-1-31 06:09:04 [ALERT] java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at java.net.URL.openStream(URL.java:1045)
	at com.creeperface.nukkit.placeholderapi.util.KotlinLibDownloader.check(KotlinLibDownloader.java:32)
	at com.creeperface.nukkit.placeholderapi.PlaceholderPlugin.onLoad(PlaceholderPlugin.kt:15)
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109)
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57)
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
	at cn.nukkit.Server.<init>(Server.java:430)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)

2019-1-31 06:09:04 [CRITICAL] Could not load plugin
cn.nukkit.utils.PluginException: KotlinLib could not be found
	at com.creeperface.nukkit.placeholderapi.PlaceholderPlugin.onLoad(PlaceholderPlugin.kt:16)
	at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109)
	at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57)
	at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:268)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
	at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
	at cn.nukkit.Server.<init>(Server.java:430)
	at cn.nukkit.Nukkit.main(Nukkit.java:109)

2019-1-31 06:09:04 [CRITICAL] 无法读取插件 'PlaceholderAPI'

**Comment by Creeperface01** [comment]
Something is blocking the IP probably.

**Comment by Creeperface01** [comment]
Download kotlin lib manually then

**Comment by D3it7i** [comment]
i have kotlin on the /plugins But still not working

**Comment by D3it7i** [comment]
@Creeperface01
