### ISSUE TITLE
kotlin lib auto update off feature please

### ISSUE THREAD

**Issue by GoodLucky777** [Creeperface01/PlaceholderAPI-nukkit#3]
Could you add feature that can off kotlin lib auto update?
I need it because i have problem with downloading(auto update) kotlin jar file from dropbox.
Please

**Comment by Creeperface01** [comment]
even you download it yourself?

**Comment by GoodLucky777** [comment]
My server can't connect to Dropbox. However, this plugin will automatically download the kotlin lib from dropbox when the server load this plugin. But my server is not able to connect with it, so it just crashes (i don't know why just crash when not able to connect with dropbox.). So I hope you can turn off automatic downloading of kotlin lib.

**Comment by GoodLucky777** [comment]
And why does it crash when plugin cannot able to auto download kotlin lib?

**Comment by Creeperface01** [comment]
But kotlinlib is required so does it download it even it is already contained in the plugins directory?

**Comment by GoodLucky777** [comment]
yes it download always so i crash always

**Comment by GoodLucky777** [comment]
log:

01:11:47 [INFO ] [PlaceholderAPI] Downloading KotlinLib...
01:11:47 [INFO ] Epoll Status is true

And server stopped. It just freeze

**Comment by GoodLucky777** [comment]
Then it gives error message:

[ERROR] Throwing
java.lang.NoSuchMethodError: cn.nukkit.utils.MainLogger.logException(Ljava/lang/Exception;)V
        at com.creeperface.nukkit.placeholderapi.util.KotlinLibDownloader.check(KotlinLibDownloader.java:37) ~[?:?]
        at com.creeperface.nukkit.placeholderapi.PlaceholderPlugin.onLoad(PlaceholderPlugin.kt:15) ~[?:?]
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:272) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:481) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]
01:13:57 [INFO ] Stopping other threads
01:13:57 [FATAL] RakNet crashed!

**Comment by Creeperface01** [comment]
ok, now with the latest version you shouldn't be getting this again if you download kotlinlib manually.

**Comment by GoodLucky777** [comment]
It works! Thank you so much!
