### ISSUE TITLE
Luckperms API Problem

### ISSUE THREAD

**Issue by IHIntary** [Creeperface01/PlaceholderAPI-nukkit#4]
I used the nukkit version of luckperms(newest),but I had some problems on placeholderapi.I can't distinguish that on luckperms or placeholderapi even if nukkit.Plz help me.
Here is the Error:
Throwing
java.lang.RuntimeException: java.lang.IllegalStateException: API is not loaded.
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
at cn.nukkit.Server.enablePlugin(Server.java:733) [server.jar:?]
at cn.nukkit.Server.enablePlugins(Server.java:722) [server.jar:?]
at cn.nukkit.Server.(Server.java:558) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.IllegalStateException: API is not loaded.
at me.lucko.luckperms.LuckPerms.getApi(LuckPerms.java:55) ~[?:?]
at com.creeperface.nukkitx.placeholders.providers.LuckPermsProvider.registerPlaceholders(LuckPermsProvider.kt:19) ~[?:?]
at com.creeperface.nukkitx.placeholders.Placeholders.onEnable(Placeholders.kt:24) ~[?:?]
at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
... 4 more

**Comment by Creeperface01** [comment]
thanks can you show me full log please?

**Comment by IHIntary** [comment]
> thanks can you show me full log please?

2019-12-29 11:53:50.085 [main] INFO  - Loading §anukkit.yml§f ...
2019-12-29 11:53:50.161 [main] INFO  - Loading §aserver.properties§f ...
2019-12-29 11:53:50.170 [main] INFO  - Selected English (eng) as the base language
2019-12-29 11:53:50.171 [main] INFO  - Starting Minecraft: BE server version §bv1.14.0§r
2019-12-29 11:53:50.177 [main] INFO  - Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
2019-12-29 11:53:50.225 [main] INFO  - Opening server on 0.0.0.0:19132
2019-12-29 11:53:50.250 [main] INFO  - This server is running Nukkit version §egit-1ac6d50§f "§b§f" (API 1.0.9)
2019-12-29 11:53:50.251 [main] INFO  - Nukkit is distributed under the LGPL License
2019-12-29 11:53:51.261 [main] INFO  - Loading recipes...
2019-12-29 11:53:51.497 [main] INFO  - Loaded 1320 recipes.
2019-12-29 11:53:51.499 [main] INFO  - Successfully loaded 0 resource packs
2019-12-29 11:53:51.556 [main] INFO  - Loading Transfer v1.0.0
2019-12-29 11:53:51.563 [main] INFO  - Loading EconomyAPI v2.0.1
2019-12-29 11:53:51.575 [main] INFO  - Loading Elementary v18.1.1
2019-12-29 11:53:51.579 [main] INFO  - Loading NPC v2.2.6
2019-12-29 11:53:51.592 [main] INFO  - Loading FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14
2019-12-29 11:53:51.601 [main] INFO  - Loading DbLib v1.0.1
2019-12-29 11:53:51.656 [RakNet Thread #16] INFO  - Epoll Status is true
2019-12-29 11:53:51.672 [main] INFO  - [DbLib] Establishing a connection withjdbc:sqlite:nukkit.db (user:nukkit)
2019-12-29 11:53:52.191 [main] INFO  - [DbLib] §eDbLib 1.0.1 created by fromgate for nukkit.ru
2019-12-29 11:53:52.203 [main] INFO  - Loading ScoreboardPlugin v1.0
2019-12-29 11:53:52.206 [main] INFO  - Loading KotlinLib v1.1
2019-12-29 11:53:52.209 [main] INFO  - Loading LuckPerms v5.0.24
2019-12-29 11:53:52.263 [main] INFO  - Loading PlaceholderAPI v1.3.1
2019-12-29 11:53:52.326 [main] INFO  - Loading Holograms v3.1.3
2019-12-29 11:53:52.339 [main] INFO  - [Holograms] Loading characters...
2019-12-29 11:53:52.402 [main] INFO  - [Holograms] Loading config...
2019-12-29 11:53:52.410 [main] INFO  - [Holograms] Loading placeholders
2019-12-29 11:53:52.412 [main] INFO  - [Holograms] Registering default grid sources
2019-12-29 11:53:52.422 [main] INFO  - Loading YakoChat v1.4
2019-12-29 11:53:52.426 [main] INFO  - [YakoChat] §fLoaded YakoChat
2019-12-29 11:53:52.426 [main] INFO  - [YakoChat] §b__     _______
2019-12-29 11:53:52.426 [main] INFO  - [YakoChat] §b\ \   / / ____|
2019-12-29 11:53:52.426 [main] INFO  - [YakoChat] §b \ \_/ / |
2019-12-29 11:53:52.427 [main] INFO  - [YakoChat] §b  \   /| |
2019-12-29 11:53:52.427 [main] INFO  - [YakoChat] §b   | | | |____
2019-12-29 11:53:52.427 [main] INFO  - [YakoChat] §b   |_|  \_____|
2019-12-29 11:53:52.429 [main] INFO  - Loading SimpleScoreboards v2.3.1
2019-12-29 11:53:52.433 [main] INFO  - Loading Placeholders v1.3
2019-12-29 11:53:52.435 [main] INFO  - Enabling LuckPerms v5.0.24
2019-12-29 11:53:52.463 [main] INFO  - §b       §3 __
2019-12-29 11:53:52.463 [main] INFO  - §b  |    §3|__)   §2LuckPerms §bv5.0.24
2019-12-29 11:53:52.464 [main] INFO  - §b  |___ §3|      §8Running on Nukkit - Nukkit
2019-12-29 11:53:52.464 [main] INFO  - 
2019-12-29 11:53:52.473 [main] INFO  - [LuckPerms] Loading configuration...
2019-12-29 11:53:52.889 [main] INFO  - [LuckPerms] Loading storage provider... [H2]
2019-12-29 11:53:53.371 [main] INFO  - [LuckPerms] Loading internal permission managers...
2019-12-29 11:53:53.419 [main] INFO  - [LuckPerms] Performing initial data load...
2019-12-29 11:53:53.559 [main] INFO  - [LuckPerms] Successfully enabled. (took 1124ms)
2019-12-29 11:53:53.560 [main] INFO  - Enabling Holograms v3.1.3
2019-12-29 11:53:53.561 [main] INFO  - [Holograms] Loading grid config...
2019-12-29 11:53:53.569 [main] INFO  - [Holograms] Loading holograms
2019-12-29 11:53:53.625 [main] INFO  - Preparing level "§aworld§f"
2019-12-29 11:53:53.711 [main] INFO  - Preparing level "§anether§f"
2019-12-29 11:53:53.714 [main] INFO  - Enabling Transfer v1.0.0
2019-12-29 11:53:53.716 [main] INFO  - Enabling EconomyAPI v2.0.1
2019-12-29 11:53:53.752 [main] WARN  - [EconomyAPI] Data provider was set to: Yaml
2019-12-29 11:53:53.755 [main] INFO  - Enabling Elementary v18.1.1
2019-12-29 11:53:53.760 [main] INFO  - §6[Elementary] §a正在加载配置文件 ...
2019-12-29 11:53:53.773 [main] INFO  - §6[Elementary] §a加载了 1 个菜单
2019-12-29 11:53:53.776 [main] INFO  - Enabling NPC v2.2.6
2019-12-29 11:53:53.797 [main] INFO  - Enabling FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14
2019-12-29 11:53:54.692 [main] INFO  - Enabling DbLib v1.0.1
2019-12-29 11:53:54.693 [main] INFO  - Enabling ScoreboardPlugin v1.0
2019-12-29 11:53:54.693 [main] INFO  - Enabling KotlinLib v1.1
2019-12-29 11:53:54.694 [main] INFO  - Enabling PlaceholderAPI v1.3.1
2019-12-29 11:53:54.696 [main] INFO  - Enabling YakoChat v1.4
2019-12-29 11:53:54.811 [main] INFO  - Enabling SimpleScoreboards v2.3.1
2019-12-29 11:53:54.816 [main] WARN  - [SimpleScoreboards] Scoreboard updating is not enabled
2019-12-29 11:53:54.816 [main] INFO  - Enabling Placeholders v1.3
2019-12-29 11:53:54.820 [main] INFO  - [Placeholders] §bNukkit placeholders loaded
2019-12-29 11:53:54.824 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.IllegalStateException: API is not loaded.
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [server.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:733) [server.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:722) [server.jar:?]
	at cn.nukkit.Server.<init>(Server.java:558) [server.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.IllegalStateException: API is not loaded.
	at me.lucko.luckperms.LuckPerms.getApi(LuckPerms.java:55) ~[?:?]
	at com.creeperface.nukkitx.placeholders.providers.LuckPermsProvider.registerPlaceholders(LuckPermsProvider.kt:19) ~[?:?]
	at com.creeperface.nukkitx.placeholders.Placeholders.onEnable(Placeholders.kt:24) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[server.jar:?]
	... 4 more
2019-12-29 11:53:54.830 [main] INFO  - Disabling Placeholders v1.3
2019-12-29 11:53:54.908 [main] INFO  - Starting GS4 status listener
2019-12-29 11:53:54.908 [main] INFO  - Setting query port to 19132
2019-12-29 11:53:54.912 [main] INFO  - Query is running on 0.0.0.0:19132
2019-12-29 11:53:54.912 [main] INFO  - Default game type: Survival Mode
2019-12-29 11:53:54.913 [main] INFO  - Done (4.882s)! For help, type "help" or "?"
2019-12-29 11:54:10.019 [main] INFO  - [CONSOLE: Stopping the server]
2019-12-29 11:54:10.020 [main] INFO  - §cUnknown command. Try /help for a list of commands
2019-12-29 11:54:10.020 [main] INFO  - §cUnknown command. Try /help for a list of commands
2019-12-29 11:54:10.064 [main] INFO  - Disabling SimpleScoreboards v2.3.1
2019-12-29 11:54:10.066 [main] INFO  - Disabling YakoChat v1.4
2019-12-29 11:54:10.066 [main] INFO  - [YakoChat] §cDisabled YakoChat
2019-12-29 11:54:10.067 [main] INFO  - Disabling Holograms v3.1.3
2019-12-29 11:54:10.078 [main] INFO  - Disabling PlaceholderAPI v1.3.1
2019-12-29 11:54:10.078 [main] INFO  - Disabling LuckPerms v5.0.24
2019-12-29 11:54:10.083 [main] INFO  - [LuckPerms] Closing storage...
2019-12-29 11:54:10.116 [main] INFO  - [LuckPerms] Shutting down internal scheduler...
2019-12-29 11:54:10.118 [main] INFO  - [LuckPerms] Goodbye!
2019-12-29 11:54:10.118 [main] INFO  - Disabling KotlinLib v1.1
2019-12-29 11:54:10.119 [main] INFO  - Disabling ScoreboardPlugin v1.0
2019-12-29 11:54:10.119 [main] INFO  - Disabling DbLib v1.0.1
2019-12-29 11:54:10.120 [main] INFO  - Disabling FastAsyncWorldEdit v19.03.29-d13b946-1257-22.0.14
2019-12-29 11:54:10.121 [main] INFO  - Disabling NPC v2.2.6
2019-12-29 11:54:10.122 [main] INFO  - Disabling Elementary v18.1.1
2019-12-29 11:54:10.122 [main] INFO  - Disabling EconomyAPI v2.0.1
2019-12-29 11:54:10.124 [main] INFO  - Disabling Transfer v1.0.0
2019-12-29 11:54:10.125 [main] INFO  - Unloading level "§aworld§f"
2019-12-29 11:54:10.153 [main] INFO  - Unloading level "§anether§f"
2019-12-29 11:54:10.235 [main] INFO  - Stopping other threads

**Comment by Creeperface01** [comment]
looks like a bug in LP

**Comment by Creeperface01** [comment]
ops I probably forgot to update to plugin. I will be able to fix it on the 1 January :/

**Comment by IHIntary** [comment]
thx~ Wait for your update!

**Comment by NTY666233** [comment]
Sorry I checked the error again and I found that this error was happened with another plugin made by you named "More Placeholder",I want to make sure that you have known about this.

**Comment by Creeperface01** [comment]
I know, but still I need to fix it 😅

**Comment by IHIntary** [comment]
> I know, but still I need to fix it 😅

Okay

**Comment by Creeperface01** [comment]
It should be fixed now

**Comment by IHIntary** [comment]
Thx It is fixed now
